services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: admin
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
