name: CI-Posts

on:
  push:
    branches: [klanthier/performance-testing]
    paths: ['apps/posts/**', 'packages/**']

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/TEST_DB?schema=public

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install

      - name: Setup env
        run: |
          echo "PROJECT_ROOT=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          echo "PROJECT_NAME=combine" >> $GITHUB_ENV
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Start docker containers
        run: |
          echo "VERSION=$(versioninfo)" >> $GITHUB_ENV
          docker-compose -f apps/posts/docker-compose.yaml up --build --detach
          sleep 10  # wait for database to be ready
          docker-compose -f apps/posts/docker-compose.yaml run bash -c "npm run generate -- --scope=posts"

      - name: Compile test
        run: |
          tsc apps/posts/test/performance/smoke-test.ts

      - name: Run k6 smoke test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: apps/posts/test/performance/smoke-test.js
        env:
          API_URL: http://localhost:3001
